name: Get CUDAQ version

outputs:
  repo:
    description: 'CUDAQ repository'
    value: ${{ steps.get-cudaq-version.outputs.repo }}
  ref:
    description: 'The branch, tag or SHA to checkout'
    value: ${{ steps.get-cudaq-version.outputs.ref }}

runs:
  using: "composite"
  steps:

    - name: Install jq
      run: |
        apt-get update
        apt-get install -y --no-install-recommends jq
      shell: bash

    - name: Get required CUDAQ version
      id: get-cudaq-version
      run: |
        repo=$(jq -r '.cudaq.repository' .cudaq_version)
        ref=$(jq -r '.cudaq.ref' .cudaq_version)
        echo "repo=$repo" >> $GITHUB_OUTPUT
        echo "ref=$ref" >> $GITHUB_OUTPUT
      shell: bash


